### ISSUE TITLE
Questions about arImportSBML.

### ISSUE THREAD

**Issue by plakrisenko** [Data2Dynamics/d2d#102]
Could you tell me please, why the last lines of the code in this function are commented?
In the model I work with there are some reactions with only a product ( -> A) and for import  to work I had to uncomment this part.

For PREDICTOR and COMPARTMENTS  sections units weren't imported. There is nothing in m.compartment(j).units, but there is information in m.unitDefinition. Can this be used? 

Best regards,
Polina

**Comment by JoepVanlier** [comment]
Feel free to add it. We'd welcome the added functionality, but keep in mind that D2D currently supports no unit consistency checking.
