### ISSUE TITLE
about the unit type and integer 

### ISSUE THREAD

**Issue by mikeaalv** [Data2Dynamics/d2d#106]
For some of my variable in my ode, I need to make the report as integer. Where can I make it in the d2d?

By the way, does the type of unit include some "limit" on values that can make my value integer? If that's the truth, where is the setting for that?

**Comment by JoepVanlier** [comment]
What do you mean exactly? As far as I am aware, D2D does not natively support integers.

What do you need this for?

**Comment by mikeaalv** [comment]
What I need is integer in some of the report(from data). These data are essentially integer, as they are disease cases reported. Some other model can also include integers. Integer is needed generally because it is the what we observe.

**Comment by araue** [comment]
Are you talking about data or parameters now?

**Comment by mikeaalv** [comment]
I am talking about data/observation here#106

**Comment by araue** [comment]
How will you link the continuous output of an ode model to integer data.
I don’t think that the software is designed for this case.
But I guess you can program some parts yourself.
