### ISSUE TITLE
differences between fixed and constant

### ISSUE THREAD

**Issue by mikeaalv** [Data2Dynamics/d2d#107]
For aFit in arSetPars, actually, I don't quite understand the differences between fixed and constant. Could you give some cases on where to use them?

**Comment by JoepVanlier** [comment]
I don't think there's a functional difference. It is more to communicate what the parameter means and to be able to differentiate between parameters you may want to free later.

**Comment by mikeaalv** [comment]
So, What's the differences between fixed and constant? Is the former means fixed by user and the latter means fixed in its own sence?
