### ISSUE TITLE
approach for variant parameters

### ISSUE THREAD

**Issue by mikeaalv** [Data2Dynamics/d2d#108]
For my model, there are some parameters with variances, such as population size in the model. What would be a proper way for this condition? I am considering using it as Observables and input in form, though it is without Error. Would this be a proper way?

**Comment by JoepVanlier** [comment]
Do you mean Mixed Effect Modelling? D2D currently does not support true Mixed Effects Models.

All observables need an error model in D2D. Even if you don't have error data, you can still estimate an error parameter.

**Comment by mikeaalv** [comment]
For population size or similar things, there is different value for every time point. However, most time, that is not regarded as observables with error. It is more like parameters or source in the ode. We probably know more precise how many people are born every year.

**Comment by JoepVanlier** [comment]
I would suggest modelling the data with an input spline.
If you're on the latest version of D2D, invoke arHelpInputs for more information.

**Comment by hhass** [comment]
issue solved?!
