### ISSUE TITLE
arStruct, additional information about the variable ar

### ISSUE THREAD

**Issue by plakrisenko** [Data2Dynamics/d2d#114]
Hi,
it is written in the wiki: "For additional information invoke help arStruct in MATLAB."
(https://github.com/Data2Dynamics/d2d/wiki/What%20are%20the%20most%20important%20fields%20of%20the%20variable%20ar%3F)

But this doesn't seem to work. Does this function exist? Can the additional information about the variable ar be found elsewhere? 

best,
Polina

**Comment by JoepVanlier** [comment]
Hey Polina,

sorry, this was changed to arHelpStruct. I will update the wiki accordingly.

Best,
  Joep.

**Comment by plakrisenko** [comment]
Oh, thank you! Looks like I need to download the latest d2d version :)
