### ISSUE TITLE
Issue with specific equations in input functions

### ISSUE THREAD

**Issue by hhass** [Data2Dynamics/d2d#115]
Hi all,

there is a strange bug in some input functions, e.g. splines, when you insert a function of parameters with brackets. E.g. the spline
monospline3(t, 0.0, knot1*(1+knot1FC), 1.0, knot2, 2.0, knot3) 
causes either a MATLAB crash or wrong sensitivities that do not allow for optimization.
In contrast, 
monospline3(t, 0.0, knot1+knot1*knot1FC, 1.0, knot2, 2.0, knot3) 
works fine.
I don't know if this behavior occurs for all input functions and if its only the brackets causing the problem.

Best
Helge

**Comment by hhass** [comment]
Joep found the bug, it was within the replacement of input function derivatives (arCompileAll).

**Comment by JoepVanlier** [comment]
Fixed in 229411f538ccb04d74b7540f8f1834bc3ae98899

![image](https://user-images.githubusercontent.com/19836026/42958270-710e6b88-8b85-11e8-978c-d684b079f482.png)
