### ISSUE TITLE
it takes a long time to load model

### ISSUE THREAD

**Issue by rosewu** [Data2Dynamics/d2d#126]
Hi, my model contain more than 1000 ODEs and it take a long time to load it. Is there any way to make it faster(for example, parallel pool)?

Thank you very much!

**Comment by JoepVanlier** [comment]
If you enable the parallel pool (parpool) then the calculation of conditions and data are handled in parallel.

Which step is taking so long? Can you profile it?
Invoke "profile" on before loading, then "profile viewer" after it has loaded.

**Comment by rosewu** [comment]
[Untitled.pdf](https://github.com/Data2Dynamics/d2d/files/2062791/Untitled.pdf)
Thank you very much for your reply!
I ran a test with ~200 ODEs and the profile is attached.

**Comment by JoepVanlier** [comment]
Are you interested in just forward simulation or also data fitting?

If you don't need sensitivities, you can turn these off, but if you want to do fitting, then you probably need them. In that case, I'm afraid that there are no options currently available in D2D for making it compile faster.

**Comment by clemenskreutz** [comment]
An additional option might be compiling with less code optimization.  Code optimization by your compiler takes a lot of time if large c files have to be compiled (e.g. several MBs). Optimizing the compiled code by your compiler can be switched off in D2D via
ar.config.no_optimization = 1

Alternatively you can specify compile options directly or edit arCompile at the point specified below.

The options/flags are compiler dependent, so it depends on your mex compiler (-> mex setup). Therefore it's possible that you have to google for the respective option for your compiler.


arCompile.m: 
(...)
    if ar.config.no_optimization == 1  || ischar(ar.config.no_optimization)   
        if ischar(ar.config.no_optimization)  % interpret the config as compiler flag
            mexopt{end+1} = ar.config.no_optimization;
        elseif ispc  % windows
            mexopt{end+1} = 'COMPFLAGS=/Od';
        else
            mexopt{end+1} = 'COMPFLAGS=''-O0''';
        end        
        fprintf('Optimization disabled\n' );
        warning('ar.config.no_optimization=1: Please carefully check, whether code-optimization really is switched off, e.g. by debugging below where mex is called.')
        fprintf('Default options can overwrite the flag set here (type cc = mex.getCompilerConfigurations). In this case change the mexopt file (see cc.MexOpt). \n');
        fprintf('Microsoft Visual C++ 2013 Professional (C) requires the following flag: %s\n', 'COMPFLAGS=/Od');
    end
(...)

**Comment by rosewu** [comment]
Thanks a lot for the reply!
I change the setup as followed, is it correct? Because I found that it took longer time when I add 'ar.config.no_optimization = 1'...

arInit;
ar.config.no_optimization = 1;
arLoadModel('Model4PBM');
arCompileAll;
arPrint
arPlot

**Comment by JoepVanlier** [comment]
Do you need to fit this model, or are you merely interested in forward simulation?
