### ISSUE TITLE
Application to neuromusculoskeletal models?

### ISSUE THREAD

**Issue by mickaelbegon** [Data2Dynamics/d2d#129]
Dear d2d developers,
I would like to know if d2d as been used or adapted to calibration of neuro-musculoskeletal model.
There are many muscle properties and your tool may be valuable!
Regards
Mickael

**Comment by hhass** [comment]
Hi Mickael,

as far as I know it has never been used for neuro-musculoskeletal modeling with muscle properties.
But you are very welcome to implement such a model. You can add issues for emerging methodological issues, and it would be great to eventually add an exemplary model to our framework.

Best
Helge
