### ISSUE TITLE
Running d2d for ODEs

### ISSUE THREAD

**Issue by ChristophStelzer** [Data2Dynamics/d2d#132]
I downloaded the latest version of d2d and ran it with MATLAB_R2018b. There seems to be a problem when using ODEs instead of REACTIONS. All example projects (containing ODEs) crash with this error:

```
Data 2 Dynamics Software
(arFramework3, def-version 3, c-version code_180926b)
Website: http://www.data2dynamics.org
Contact: Andreas Raue - andreas.raue@fdm.uni-freiburg.de
Copyright 2016 D2D Development Team. All rights reserved.

Clearing old D2D mex files from memory  [OK]
loading model #1, from file Models/TwoStepSynthesisWithGlu.def...
Index exceeds the number of array elements (0).

Error in arCheckForNegFluxes (line 5)
        reversible = ar.model(m).reversible(jf);

Error in arLoadModel (line 1082)
    arCheckForNegFluxes(m, fid);

Error in Setup_IndiBac (line 5)
arLoadModel('TwoStepSynthesisWithGlu');
```

I ran it with multiple models and also with a model of myself (which used to work with a previous release of d2d/MATLAB_R2015a) and all of them show the same error. 

Any idea/help?
Christoph

**Comment by JoepVanlier** [comment]
Thanks for the bug report. I just committed a fix for this here 470634347ffea15e3d634976d7f35871c14b5ae7

You have two options, either update to the version I just committed. Or setting ar.config.checkForNegFluxes to 0. Either should get you back up and running.

Best,
  Joep.
