### ISSUE TITLE
Problem when executing arMergeFits in an "empty" model

### ISSUE THREAD

**Issue by elbaraim** [Data2Dynamics/d2d#137]
If I load a model in which I never did a multi-start optimization, the ar.ps struct does not exist (same for ar.chi2s).
Then if I call `arMergeFits` it checks for existence of `ar.ps` in the "empty" model, which does not exist. And I am not able to load the results from already existing multi-starts.

- This is an example of my code:

```
clear all
close all
clc

load('model_name.mat','ar'); % this is the "empty" model
arMergeFits;

% some plotting
```

Is there a way I can circumvent this problem?

**Comment by adrianhauber** [comment]
Hi Elba,

sorry for the late respose… This should be fixed with the commit 222ce99e8aee1200306e6ec0682b5b2e9146b107.

Best
Adrian
