### ISSUE TITLE
Missing Parameter in Crauste example

### ISSUE THREAD

**Issue by jvanhoefer** [Data2Dynamics/d2d#143]
I was just looking into your implementation of the Crauste Modell (Cell Systems 2017) and was wondering, why the parameter mu_EL was missing (and therefore the Reaction  L+E -> L). I would have guessed, that the reaction "EarlyEffector   ->  " would have the propensity "mu_EL \*EarlyEffector\* LateEffector"

Is there a particular reason for this?

Thank you
Jakob

**Comment by LoosC** [comment]
This is the final model used by Crauste et al. In Table S3 of the Cell Systems Paper you see that for this particular model the parameter mu_EL is 0 and thus not present in the model.
