### ISSUE TITLE
Parsing error in R2019b

### ISSUE THREAD

**Issue by ryvinec** [Data2Dynamics/d2d#144]
Hi,

I'm unable to load any model file, due to a Parsing error.
I'm using a trial version of Matlab R2019b, with optimisation and symbolic toolbox.
Thanks for your help!
Romain
---
>> clear all;
arInit
Data 2 Dynamics Software
(arFramework3, def-version 3, c-version code_171219b)
Website: http://www.data2dynamics.org
Contact: Andreas Raue - andreas.raue@fdm.uni-freiburg.de
Copyright 2016 D2D Development Team. All rights reserved.

Clearing old D2D mex files from memory  [OK]
>> arLoadModel('ABC_model');
loading model #1, from file Models/ABC_model.def...

ans =

    17

Error using arParsingError (line 8)
Parsing error in REACTIONS at p1*A_state in model 1 in ABC_model.def

Error in arLoadModel (line 362)
                            arParsingError( fid,  'Parsing error in REACTIONS at %s in model
                            %d', str{1}{:}, m );

**Comment by clemenskreutz** [comment]
Is this an error that does only occur for R2019 by and not older Matlab Releases? 
Did you check that on your computer?

**Comment by ryvinec** [comment]
I used on the same computer D2D with R2016b, working properly, i have never seen that error before.
I cannot try other versions in between, though.

**Comment by adrianhauber** [comment]
I cannot reproduce this issue on R2019b, was probably resolved by a newer commit. Please re-open if it still persists.
