### ISSUE TITLE
Specification of PARAMETERS section in model definition files

### ISSUE THREAD

**Issue by gdudziuk** [Data2Dynamics/d2d#145]
Concerning the PARAMETERS section in model definition files, the wiki of d2d states that:

> In this optional section the default settings for parameter can be specified. Please note that the intension of this section is to save final parameter values for documentation purpose.

This is exactly what I want to do now. I have fitted a model to some data outside Data2Dynamics (using just custom Matlab code). I would like to share the fitted model and its parameters as a d2d model file. However, in the wiki, there is no explicit specification of the correct content of the PARAMETERS section. Would it be a problem for you, d2d maintainers, to briefly describe each argument of the PARAMETERS section, similarly as it is done in the wiki for other sections of the model definition files?

**Comment by clemenskreutz** [comment]
Dear gdudziuk.

The PARAMETERS section is added at the end of the def files (below the CONDITIONS section).
Specification is as follows:
PARAMETERS
//name	value	doFit	dolog	lowerBound	upperBound
offset	 0	 1	 0	 -100	 100
signum	 1	 0	 0	 -1	 1

In the examples folder, there are some example, e.g. DallaMan2007, Casaletto_PNAS2019, Steckmann2012_Fibrillogenesis, ...

These values are permanently stored in D2D in the global variable ar (ar.pExtern, ar.qFitExtern, ar.qLog10Extern, ar.lbExtern, ar.ubExtern).

**Comment by gdudziuk** [comment]
> //name value doFit dolog lowerBound upperBound

This is what I was looking for. So the arguments in the PARAMETERS section are as those of the function `arSetPars`. Thanks! 

IMHO, it would be beneficial to add such info to the wiki. E.g. to explain therein that in the PARAMETERS section the 1st argument is the parameter value, the 2nd argument is a flag indicating whether the parameters is subjected to fitting or not, etc. Or just mention that the arguments in this section are as the arguments of `arSetPars`.
