### ISSUE TITLE
Delay differential equations model

### ISSUE THREAD

**Issue by bartekli** [Data2Dynamics/d2d#158]
Is it possible to implement DDE Model in d2d? If so, can dde23 solver be used, or should the equations be defined in other way?

I would be grateful for any insights!
Best,
Bartek

**Comment by clemenskreutz** [comment]
Dear Bartek.
DDEs are not supported. 
The only way to deal with delays is the so-called linear chain trick.
See for example in Examples\ToyModels\ChainLength_Estimation

Best, Clemens.
