### ISSUE TITLE
TurboSplines test is failing

### ISSUE THREAD

**Issue by adrianhauber** [Data2Dynamics/d2d#164]
I traced this back to commit 6a953fa6b47bf0c0fa4c362ebdcbc98fdcb19cef by @clemenskreutz. The log file is looking like this:
```
04-Aug-2020 18:33:22    working
07-Aug-2020 16:15:16    errors in ResponseCurve
07-Aug-2020 22:10:14    errors in TurboSplines ResponseCurve
07-Aug-2020 23:35:22    errors in TurboSplines
```

**Comment by clemenskreutz** [comment]
It is fixed now (12.4.21). 
It seems that I accidentially deleted lin 2396 in the above-mentioned commit.
