### ISSUE TITLE
SBML without observables specified

### ISSUE THREAD

**Issue by sl6zq** [Data2Dynamics/d2d#169]
Hi,

I'm trying to use d2d on my SBML model with my own experimental dataset. 
I loaded the sbml model using arParseSBML then arLoadModel, which created the model's .def file. 
In my model's .def file, however, I don't have any observables defined. I tried manually adding in the observables that match with the variable for which I have data. However, I get an error that tells me that the variable is already defined in INPUTS. 
Do you have any recommendation for resolving this issue?
Thank you.

**Comment by adrianhauber** [comment]
HI Sarah,

could you provide the model .def file that lead to this error?

Best,
Adrian

**Comment by sl6zq** [comment]
Hi Adrian,

Thank you for the reply. I've attached the .def file.

Best,
Sarah

**Comment by sl6zq** [comment]
Hi Adrian,

I was just wondering if you have found any particular issue with the .def
file I sent. I've noticed that an example model like ChenMSB2009 also
doesn't have observables specified but was still able to match the
variables in the model with those in the data. Thank you!

Best,
Sarah

**Comment by chrischdjan** [comment]
Hi Sarah, 

could you please try again to provide us with your .def file? It's not included in your reply.

If you get an error that says that the variable is already defined in INPUTS, then you might simply rename the input variable (also in the ODEs/Reactions/Equations) or you rename your observable variable (also in your data). 

Regarding the ChenMSB2009 example: There are indeed no observables defined in the model.def. Instead they are defined in the individual .def files of the data sets in the /Data folder. This is the recommended way for using multiple data sets.

**Comment by sl6zq** [comment]
Hi Christian,

I was able to get the code to read my .def file after renaming the
observable variable. Thank you!

Sarah
