### ISSUE TITLE
Documentation for PLE calculation on cluster

### ISSUE THREAD

**Issue by leshaker** [Data2Dynamics/d2d#68]
Originally reported by: **Katja Tummler (Bitbucket: [ktummler](https://bitbucket.org/ktummler), GitHub: Unknown)**

----------------------------------------

Hej all,

we tried to calculate profile likelihoods with arPLECalcCluster, which works fine (and is also pretty cool). However, its a bit unclear to us how the results are saved, meaning that after the cluster job has finished, we could not find the results in the ar.ple structure, where we think they belong.

Could you offer some example code or a short outline of how to best use the functions and access the results?

Thanks and many regards,
Ximena & Katja

----------------------------------------
- Bitbucket: https://bitbucket.org/d2d-development/d2d-software/issue/68

**Comment by leshaker** [comment]
Hi Katja,
I added a first minimal description in the [wiki](https://github.com/Data2Dynamics/d2d/wiki/How%20to%20run%20PLE%20calculations%20on%20a%20Cluster). Please feel free to add helpful comments for other users.
Max

**Comment by KatjaT** [comment]
Hej Max,

wonderful, thanks. We'll add things we come across along the way.

Katja
