### ISSUE TITLE
Problems with arSteadyState and pre-equilibration

### ISSUE THREAD

**Issue by KatjaT** [Data2Dynamics/d2d#69]
We have a problem when trying to pre-equilibrate the following example model with 3 states thereof one non-steady-state species. @JoepVanlier: Could you please check what's going wrong in the simulation? It seems to be a problem in arSimuCalc and it only happens if not steady state species should be assigned as omitted species.

Thanks,
Ximena, Katja (& Max)

[example_equilibration.zip](https://github.com/Data2Dynamics/d2d/files/336634/example_equilibration.zip)

**Comment by JoepVanlier** [comment]
Thanks for the report, I will have a look at it.

**Comment by JoepVanlier** [comment]
I think I fixed it. Let me know if there are any further issues. Feel free to re-open if new problems arise :)

Best,
Joep.

**Comment by KatjaT** [comment]
Thank you for the quick help, Joep!
It works fine now, also for our real model.

All the best
Katja
