### ISSUE TITLE
"ar" variable in equations

### ISSUE THREAD

**Issue by araue** [Data2Dynamics/d2d#70]
Hi all,

Here is an issue that a somebody at the qBio Summer School 2016 in New Mexico noticed...

Have you ever tried to used a variable called `ar` ?
There is a kind of critic error message, see below.
I am not sure how to best throw and error if users try to use a variable with that name.

Any ideas?

Andreas

```
Error using sym/subsref (line 781)
SYM objects do not allow nested indexing. Assign intermediate values to variables instead.

Error in arLoadModel (line 559)
if(~isempty(ar.model(m).u))

Error in MySetUp (line 4)
arLoadModel('EGFR_fluorescence');
```

**Comment by JoepVanlier** [comment]
Seems to be caused by the eval statements further down the line. Not sure what purpose they serve. I've commented them out. Seems to still pass the integration tests when commented out.
