### ISSUE TITLE
Files missing, who has them?

### ISSUE THREAD

**Issue by araue** [Data2Dynamics/d2d#71]
This folder is empty but shouldn't, right?
C:\Users\araue\Documents\Workspace\d2d\arFramework3\ThirdParty\matlab2tikz

**Comment by leshaker** [comment]
do you have git installed (also in the command line/CMD)? and what version of Matlab are you using? Because I implemented several different ways to pull the third party modules depending on the system but I couldn't test all of them...

**Comment by leshaker** [comment]
@araue Could you please tell me what `[has_git, is_repo] = arCheckGit(repo_path)` returns when adapt the repo_path to your location of d2d?

**Comment by araue** [comment]
Hi, the result is:

```
>> [has_git, is_repo] = arCheckGit(repo_path)

has_git =

     1


is_repo =

     1
```

**Comment by leshaker** [comment]
ok, and does `arUpdateD2D` work?

**Comment by araue** [comment]
No the files are back there so I guess this is a problem on my side. Sorry for the trouble and thanks for the help!
