### ISSUE TITLE
arConfig

### ISSUE THREAD

**Issue by JoepVanlier** [Data2Dynamics/d2d#72]
I wanted to set up a quick script for setting some user specific configuration (things like default nCVRestart and such). I noticed that there was already an arConfig.m. However, when I try to call it, it says the fig file corresponding to it is missing.

What was arConfig used for? Is it still used/necessary/desirable or can this file be removed?

**Comment by araue** [comment]
Hi, I would say this is some kind of dead file. I don't recall coding it, but the code looks like it could come from me. I say, go ahead and replace it... Thanks!
