### ISSUE TITLE
Ceres solver not working properly?

### ISSUE THREAD

**Issue by leshaker** [Data2Dynamics/d2d#74]
Hi all, 

could somebody please check if he/she gets the ceres-solver to work? I ended up with some compilation problems... Perhaps it's due to the new structure of the ThirdParty folder?

Max

**Comment by clemenskreutz** [comment]
I'll try to check.
From discussions with Franz-Georg, I remember the following issues:

- Compiling requires new versions of the compilers
- At some windows computers there was the error that some Bessel functions are not found.
- For some unix systems (e.g. knechte in Freiburg) the following workaround had to be done:

> Compiled Ceres C++ code may not run under unix because of old C++ libraries. Moreover, Matlab prefers using the compiler version provided by the matlab installation instead of potentially newer version on the system. 
> There seems to be no commands to force Matlab using other librarires. Using symbolic links can solve this issue:
> // Backup the old library
> $ mv        /opt/MATLAB/R2016a/sys/os/glnxa64/libstdc++.so.6 /opt/MATLAB/R2016a/sys/os/glnxa64/libstdc++.so.6.old
> 
> // Creating a symbolic link
> $ ln -sf     /usr/lib/x86_64-linux-gnu/libstdc++.so.6            /opt/MATLAB/R2016a/sys/os/glnxa64/libstdc++.so.6
> 
> This of course only solves the problem for a specifc matlab version (Matlab 2016a in the example). For other versions, the commands/paths have to be adapted accordingly.
>

**Comment by leshaker** [comment]
I should have read the README.txt first :-) I needed to replace the config.h in the ceres-solver directory which went missing because of my update of the submodules. I added a step to automatically copy the customized file to the compileCeres script to avoid future confusion...
