### ISSUE TITLE
max in output function

### ISSUE THREAD

**Issue by LoosC** [Data2Dynamics/d2d#75]
Hi all,

is there a way to use the max function in the output, for example like

OBSERVABLES
y     C   "au"   "conc."    0   0 "max(x,0.1)"

which produces errors due to undefined symbols when compling.

Best,
Carolin

**Comment by rengesser** [comment]
Hi Carolin,

you can try to implement the maximum with the function:

`max(a,b) = 1/2 * (a+b+sqrt((a−b)^2))
`
Best,
Raphael

**Comment by LoosC** [comment]
Hi Raphael, 

thanks for the fast response!

Best,
Carolin
