### ISSUE TITLE
How to import an SBML model?

### ISSUE THREAD

**Issue by matthiaskoenig** [Data2Dynamics/d2d#76]
Hi all,
How can I import an SBML model in d2d ?
I could not find any function for that. My model definitions (ODEs) are all in SBML and want to use d2s for the parameter fitting task. I.e. model structure exists, I just want to add data and conditions and fit a subset of parameters from the SBML.

Also what is the best way to ask questions? I could not find any forum, so I try it here.
If there is some development/help group please let me know. 

The best 
Matthias

**Comment by rengesser** [comment]
Hi Matthias, 
have you already tried the function: 

`arImportSBML`

Best,
Raphael

**Comment by matthiaskoenig** [comment]
Hi Raphael, 
thanks for that. Did not see the function.

Fixed a bug with the libsbml path on linux on the way.
https://github.com/Data2Dynamics/d2d/pull/77
Could someone with commit rights merge this.

M

**Comment by matthiaskoenig** [comment]
Unfortunately I have changing compartment volumes in my model which are not supported by d2d.
```
Error using arImportSBML (line 102)
non-constant compartments are not yet supported in D2D!
```
Is there any plan on implementing this?
Volumes often change dynamically (RateRules) in biological models, like in cell growth.

**Comment by matthiaskoenig** [comment]
I now changed all my RateRules for compartment volumes to InitialAssignments, i.e. all compartment volumes are constant.

But the SBML import still fails, now with 
```
arImportSBML('caffeine_pkpd_4.xml')
Error using  | 
Inputs must have the same size.

Error in arImportSBML (line 123)
        israterule = israterule | strcmp(raterulespecies(i),{m.species.id});
```
Model is attached (valid SBML checked with SBML validator):
[caffeine_pkpd_4.xml.zip](https://github.com/Data2Dynamics/d2d/files/613617/caffeine_pkpd_4.xml.zip)

Any help is appreciated.

**Comment by matthiaskoenig** [comment]
The problem is that D2D does not support SBML parameters which are calculated via RateRules. 
Such definitions should be translated directly into ODEs, i.e. the
dxi/dt = f()
which are defined in SBML rate rules on parameters should be translated to the ODE section of the d2s model.

Many ode models cannot easily be encoded in the species-reaction schema of SBML, so some/all of the ods are written as rate-rules on SBML parameters. These are not parameters which should be optimized, but interpreted as states.

How would I encode a model of the following form in d2d?
---
A --v1--> B, with A and B species in compartment V, converted by reaction v1
v1 = k1*A
and a signal variable S defined via
dS/dt = k2*A*B 
which is not a species and not in any compartment 
---
the dS/dt equation is what RateRules on parameters are

If somebody could show me how to write such a model in d2d I could update the SBML importer code to create the correct d2d model.

In addition the SBML units are not read from the SBML when creating the d2d model (this is a minor issue, but should be implemented).

**Comment by bernhardsteiert** [comment]
Hi Matthias,

My suggestion would be to define a new species S and write the RateRule in the following way (in the model.def):

```
STATES
S_state             C   au      conc.	1

REACTIONS
           ->  S_state        CUSTOM "k2*A_state*B_state"
```

Please note that state names have to be longer than one character, therefore I added "_state".

Best,
Bernhard

**Comment by matthiaskoenig** [comment]
I need states which are not concentrations and do not have an associated
compartment. Is this possible and can I mix such states with classical
species states? Do I need to use reactions or could I write the odes
directly in the ode section?

**Comment by bernhardsteiert** [comment]
From a mathematical point of view, it does not matter if a state represents a species, or concentration, or anything else. The lines from my previous comment implement dS/dt = k2*A*B. Set the initial value to zero (init_S_state "0" under CONDITIONS) and you should be fine.

For specification you have to choose: Either REACTIONS, or ODES as keyword (most people use the former). Both at the same time is not possible.

Compartments are only important when mass is transferred from one to the other. In your case, it should be appropriate to assign S to the same compartment as A and B.

Best,
Bernhard

**Comment by matthiaskoenig** [comment]
This issue is not solved, I will open a new one with a clearer description.
