### ISSUE TITLE
SBML compartment handling not conform standard

### ISSUE THREAD

**Issue by JoepVanlier** [Data2Dynamics/d2d#78]
There's an issue with the SBML import/export for multi-compartment models.

SBML typically uses a different compartment convention than we do in D2D. In D2D, reactions are always specified using concentrations relative to the origin of the reaction, while the SBML standard uses total amounts for the kinetic laws (see: http://co.mbine.org/specifications/sbml.level-3.version-1.core.release-1.pdf (L3V1) and http://co.mbine.org/specifications/sbml.level-2.version-4.release-1.pdf (L2V4) )

I do think the SBML standard is less error prone (for example: diffusion has the same rate forward and backward, while this is not the case in our standard; we have to explicitly multiply the backward reaction with a volume ratio), but it seems a bad idea to change this convention in D2D, since it'd break existing models and make single compartment models with estimated parameters (which are the majority) look more complicated than they have to be. In most cases, our estimated parameters are unequal and absorb these volume ratios anyway.

I do think however, that we should make sure that import and export conform standards. arExportSBML conforms to the standard as long as 'copasi compatibility' is set to 1.  There is however no such feature for arImportSBML.

I tested the arImportSBML functionality with a simple diffusion model with unequal compartment volumes and the SBML file does indeed not import correctly. arExportSBML works conform standard when the copasi flag is set to 1.

So two suggestions:
1. Make 'copasi' export the default since this is what is described in the SBML standard docs.
2. Add 'copasi' import functionality to SBML import (which currently does not exist) and make this the default.

Any objections to these changes?

Best,
Joep.

**Comment by leshaker** [comment]
Hey Joep,
I was aware of this issue in the importer and tried to fix it a while ago (mainly in this commit https://github.com/Data2Dynamics/d2d/commit/c2c1f0fdaa526f9d9996fba9e187f37c0821b45a) but only succeed for some classes of models. So I vote for both of your propositions as the SBML import/export capabilities of D2D have not gotten enough attention until now.
Thanks!
Max

**Comment by JoepVanlier** [comment]
So, I've done an initial commit on this.

For my test cases this commit solved the issue. The SBML test suite still fails a lot of tests, but it did not seem to get worse (I could oddly enough not find one with two different compartment volumes, but not having varying compartments). Also made copasi the default.

I will continue this next week. If there are any urgent issues before then, feel free to undo my commit.

**Comment by JoepVanlier** [comment]
With the changes made in the last two years, it is now conform the standard.
