### ISSUE TITLE
ABC_model.def issues

### ISSUE THREAD

**Issue by DhruvaDhruva** [Data2Dynamics/d2d#79]
When I run Setup on the ABC_model, the following error displays:

Error using doPPL
Too many input arguments.

Error in Setup (line 25)
doPPL(1,1,1,linspace(0,100,11),0,1,0.25);

This seems very reasonable, as the function file for doPPL is given as:

function doPPL(m, c, ix, t, takeY, options)
....
end

, which has 6 inputs rather than the 7 listed on the setup file. 

Thanks

Best

Dhruva

**Comment by hhass** [comment]
Hey Dhruva,

thanks for your comment.
I made some major changes on the doPPL function and forgot to update the ABC example. I will do it during the evening, it would be great if you can try the toy example again tomorrow.

Best
Helge

**Comment by DhruvaDhruva** [comment]
Thanks a lot! I will try and let you know. As a side question, does the profile likelihood functionality continue to work if the .def file is written in terms of differential equations, rather than reactions?

Many Thanks

Best

Dhruva
________________________________

**Comment by hhass** [comment]
Hey Dhruva,

sure, the way you define a model does not alter the functionality of the framework. These are just two ways to define the model for your convenience and d2d has to distinguish how to include them in MATLAB.

Best
Helge

**Comment by hhass** [comment]
Hey Dhruva,

we just made some major changes on the script and folder structure. The ABC toy model switched to the folder Examples/ToyModels/.
But running prediction bands again on ABC is very easy so you can do it on your local copy. Simply run

doPPL(1,1,1,linspace(0,100,11),1)

instead of the old line.

Best
Helge

**Comment by DhruvaDhruva** [comment]
Thanks a lot! I ran the new code and it works :).
________________________________

**Comment by DhruvaDhruva** [comment]
Dear Helge,

Thanks again for your advice. I was wondering if I could trouble you with one more question/verification:

I have attached a zipped folder containing the NfKb metabolic network described in "Mathematical model of NF-kB Regulatory Module" (Lipniacki et al, Journal of Theoretical Biology 2004 ). Note that I generated synthetic data which exactly describe the time-course at the nominal parameter values.

If you unzip the attached folder in the "Examples" folder of the ar3 Framework and run the Setup file, the model is loaded and ple('k2') is run. The profile likelihood output should be the same as in the svg file i attached.

My first question is why the residual ar.res is nonzero. Given my synthetic data perfectly matches the model output, it should be zero. Or does ar.res not represent the residual between model output and data?

The output of the attached .svg seems strange to me. I know a priori that the product "k2*c4" is structurally unidentifiable. Indeed, the output of ple('k2') is that k2 is unidentifiable, and that c4 changes with k2 over the unidentifiability (see attached svg). However the lower graph of the .svg file, i.e. the 'change of other parameters' graph, does not reflect this. Have I generated the profile likelihood of k2 correctly in my setup file?

Thanks so much

Best

Dhruva



________________________________
From: Dhruva Raman [dhruva.raman@lmh.ox.ac.uk]
Sent: 04 January 2017 19:11
To: Data2Dynamics/d2d; Data2Dynamics/d2d
Cc: DhruvaDhruva; Author
Subject: RE: [Data2Dynamics/d2d] ABC_model.def issues (#79)

Thanks a lot! I ran the new code and it works :).
________________________________
