### ISSUE TITLE
excessive trailing space in arCompile.m

### ISSUE THREAD

**Issue by FFroehlich** [Data2Dynamics/d2d#83]
the space in

https://github.com/Data2Dynamics/d2d/blob/master/arFramework3/Subfunctions/arCompile.m#L507

breaks compilation (when number of conditions exceeds chunksize) on some linux systems and should be removed.

Also I would generally advise using fullfile(path,to,file) instead of strings with backticks/slashes as it makes cross-system compatibility a generally less painful.

**Comment by JoepVanlier** [comment]
Thanks for the report and good suggestion!

The problem doesn't occur on my local system, so could you check whether the last commit fixed it?
