### ISSUE TITLE
Problem with arCompile

### ISSUE THREAD

**Issue by Coolak64** [Data2Dynamics/d2d#84]
When trying to run through the Bachmann_MSB2011 example with the data2dynamics software package, the code works fine up until the following error messages:

calculating data m1 d40 -> c12, CFUE_DoseResp_CIS_90min...skipped
calculating data m1 d41 -> c13, CFUE_DoseResp_CIS_90min...skipped
calculating data m1 d42 -> c14, CFUE_DoseResp_CIS_90min...skipped
Compiling files...
Error using mex
No supported compiler or SDK was found. You can install the freely available MinGW-w64 C/C++ compiler; see Install
MinGW-w64 Compiler. For more options, visit http://www.mathworks.com/support/compilers/R2016b/win64.html.

Error in arCompile (line 253)
            mex('-c',verbose{:},mexopt{:}, '-DNTIMER', '-outdir', ['Compiled/' c_version_code '/' mexext '/'], ...

Error in arCompileAll (line 496)
    arCompile(forcedCompile, false, false, source_dir);

I have installed the MinGW-w64 C/C++ compiler and this same error keeps popping up. What could the issue possibly be? All help is extremely appreciated.

**Comment by araue** [comment]
You did not set up your mex compiler properly. Please check with the Mathworks support, this is not an issue of the D2D code.
