### ISSUE TITLE
How to use multiple datasets: one dataset per the corresponding initial condition? 

### ISSUE THREAD

**Issue by evgeni-nikolaev** [Data2Dynamics/d2d#86]
Greetings,
I have question on how to set up a model which describes a plasmid replication. Eight datasets were collected, each for the corresponding initial concentration of the plasmid. So, we have built a mathematical model with one nonzero initial condition, say, A(0), and other variables with zero initial condition conditions. The general ODE model is 
X' = F(X,p), where X = (A,B,C,G) is the state vector
A(0) = Ak, (k=1,2,...,8) - different initial conditions  one for each experiment.  
B(0) = 0
C(0) = 0 
G(0) = 0
For each Ak, we have measured  the corresponding Gk(t) and std_k(t), where G = GFP, and all measurements are placed in one excel file with 17 columns:
t G1(t) G2(t) ... G8(t) std1(t) ... std8(t)
I would be very grateful if you could please give me your advice on what what would be the best way to set up the model and data in d2d? Thank you in advance.
-Evgeni.

**Comment by JoepVanlier** [comment]
If you want to estimate the initial conditions as parameters:
Simplest would be to just split the excel file into 8 files and have a different parameter names under the CONDITIONS section for each experiment.

If you wish to do this within a single data file, what you can do is make use of the RANDOM keyword. This designates a specific keyword which is searched for within parameter names and adds an index based on a column with the identical keyword in the data file (see Examples/ToyModels/MultiCondition_Test for an example on how to use this).

If you don't want to estimate the initial conditions but just specify them then you only need a column in the excel file with the parameter name that you want replaced in each of the experiments.

Note that the different experiments have to be on different rows for this to work in any of the options.

**Comment by JoepVanlier** [comment]
I am assuming this issue is solved. Feel free to open a new one if you have further questions.
