### ISSUE TITLE
SBML ODE model

### ISSUE THREAD

**Issue by chiaraunipg** [Data2Dynamics/d2d#87]
Hi,
I have written a model using ODE instead of reactions. I would like to translate it in SBML using the function arExportSBML. However, it gives me the following error:

Error in arExportSBML (line 215)
        if(isfield(ar.model(m),'v') && ~isempty(ar.model(m).v{jv}))

I think this is due to the fact that the variable ar.model.v is empty. How can I fix it?
Thank you in advance.

Chiara

**Comment by hhass** [comment]
Hi Chiara,

this issue should be fixed through commits on 5th and 8th of March 2018.
Please reopen the issue if you still observe problems with empty model.v.

Best
Helge
