### ISSUE TITLE
 Extended Functionalities and Function Reference

### ISSUE THREAD

**Issue by evgeni-nikolaev** [Data2Dynamics/d2d#89]
Hi! I have found a weblinks to **Extended Functionalities** and **Function Reference**  opening empty web pages, while reading the description for the model entitled **Raia_CancerResearch2011** on the webpage **https://bitbucket.org/d2d-development/d2d-software/wiki/Raia_CancerResearch2011**. I would be very much interested to use both resources: **Extended Functionalities** and **Function Reference**. Do you still plan to write them and upload to the corresponding webpages or do the resources already exist and are just moved to some other web pages? Thank  you in advance, Evgeni.

**Comment by araue** [comment]
I fixed some of the links. Please check if it is now working...
