### ISSUE TITLE
an explicit tutorial

### ISSUE THREAD

**Issue by evgeni-nikolaev** [Data2Dynamics/d2d#90]
Sorry for somewhat repetitive question. I am new to the D2D software and I am completely lost. My model is very similar to **Raia_CancerResearch2011** and initially I was very optimistic to start learning powerful D2D functionalities by example and now I see that this showcase and other showcases to do not teach useful techniques how to run an optimization task. The showcases just load already optimized models and plot them. For example, it is not obvious how to set up the parameter bounds, min and max values, it is not obvious how to select an optimizer, it is not obvious how to set parameters for likelihood profile routine etc. I would be very grateful to you if you please help me with these elementary steps.

**Comment by araue** [comment]
See my previous comment

**Comment by mahdiarsadeghi** [comment]
I am also trying to understand how d2d works. I cannot see your previous comment.

**Comment by adrianhauber** [comment]
Please check out the articles under the section 'Basic introduction' in our wiki: https://github.com/Data2Dynamics/d2d/wiki

**Comment by clemenskreutz** [comment]
Maybe this also helps:
https://link.springer.com/protocol/10.1007/978-1-4939-9102-0_16
