### ISSUE TITLE
showcases

### ISSUE THREAD

**Issue by evgeni-nikolaev** [Data2Dynamics/d2d#91]
Hi again,
This is my third email on the same topic related to a tutorial and showcases on how to learn efficiently and quickly the D2D powerful features. So, I want to apologize in advance for taking your time up, answering my emails. I think that it would be much more helpful for the community, if ALL showcases are replaced by working examples that demonstrate how to set up all parameters including parameter bounds, and which would actually carry out parameter fittings, including PLE, and both deterministic and Bayesian approaches. What is the value to watch showcase figures and plots without any understanding of which parameter settings were used when each showcase loads already somehow optimized parameter values to generate the plots? We want to learn how to use the tool to fit the parameters using the features of the tool and the features are absent from the showcases! Do you think you could please upload actual Setup files that include the parameter setups and arFit so that we can see the process. Specifically, can you upload a real Setup with all true D2D parameter settings which would replicate calculations shown in your Youtube video? Thank you in advance!!! -Evgeni.

**Comment by araue** [comment]
Hi Evgeni, 

Thanks for this comment!
You are right about many things and we would certainly like to do this.
However, keep in mind that nobody pays us for developing this software.
We rely on the contribution of everybody.

So my suggestion is, if you feel strongly about this, please contribute a working example.

Andreas
