### ISSUE TITLE
L1 penalization when all parameters are cell-specific 

### ISSUE THREAD

**Issue by ryvinec** [Data2Dynamics/d2d#92]
Hi,
I encounter a bug in line 30-31 of l1Selectopt.m:
"tmp = find(signifmat(1,:) < 0);
final_ind = tmp(end);"

When the optimization cannot find parameters to fix to 0 (the full model is already the most parsimoneous one), the variable "tmp" above is empty and line 31 causes an error.

May be one can add an if statement, and select the full model if tmp is empty (a warning concerning the threshold for parameters to be taken at 0 could be helpful too)

Thanks in advance,
Romain

**Comment by bernhardsteiert** [comment]
Thanks Romain for pointing this out!

Cheers,
Bernhard
