### ISSUE TITLE
L1 Plot draws empty plots

### ISSUE THREAD

**Issue by ryvinec** [Data2Dynamics/d2d#93]
Hi,

I haven't been able to understand why,
but l1Plot.m does not seem to work properly.
After using l1Init, l1Scan, l1Unpen, l1SelectOpt and l1Tree,
the function l1Plot produces empty plots for subplot(2,2,[2,4]) and subplot(2,2,1) (while all results seems to have been save properly in the ar structure.

Thanks for your help!

Romain

**Comment by bernhardsteiert** [comment]
Hi Romain,

Without an example, it is impossible to tell what is going wrong. Please check if arFramework3/Examples/Merkle_ToyModel_PCB2016/SetupL1_final.m runs without errors.

Best,
Bernhard

**Comment by JoepVanlier** [comment]
Closed after long period of inactivity after no example was provided.
