### ISSUE TITLE
running doTests on Windows

### ISSUE THREAD

**Issue by plakrisenko** [Data2Dynamics/d2d#95]
Hello!

It looks like in the file /arFramework3/Examples/doTests.m, in the function doTest, line 90

`[~,dir] = system(sprintf('find %s -type d -name "%s"',example_folder,dir));`

doesn't work for windows. 

I think this should work:
`    if isunix`
`        command = sprintf('find %s -type d -name "%s"',example_folder,dir);`
`    else`
`        command = sprintf('dir "%s" /AD /b /s | findstr /r "%s$"',example_folder,dir);`
`    end `
`    [~,dir] = system(command);
`

Probably you know better way of fixing it.

best regards,
Polina

**Comment by araue** [comment]
Hi Polina,

Thanks for reporting this and suggesting a solution.
If the fix you propose work on your (Windows) system, please feel free to submit it to the repository.

The software replies on creative solutions from users! ;-)

Cheers,
Andreas

**Comment by JoepVanlier** [comment]
I've pulled your suggestion into the repository, Polina.
Thank you for your contribution!

Best,
  Joep.

**Comment by plakrisenko** [comment]
Thank you very much for the fix!
 
We couldn't make the toolbox work on Windows though (both Windows 7 and 10). 
Unfortunately, I cannot explain properly what was the last problem as I don't have Windows myself. It was something mex compiler related. So, we've installed ubuntu in the end)
