### ISSUE TITLE
Delay differential equations

### ISSUE THREAD

**Issue by Athithan27** [Data2Dynamics/d2d#99]
Hi,
Is it possible to use time delay using delay differential equations? I want to estimate time delay as a parameter
If yes, Could you please share me some example? It would be a great help

Thanks in advance

With regards,
Vimal

**Comment by rengesser** [comment]
Hi Vimal,

the functionality of Data2Dynamics does not support delay differential equations (DDE). However, you can try to approximate the DDE by a system of ordinary differential equations using the linear chain trick. In the linear chain trick a delay is modelled by a series of intermediate states. It is used in the examples [Bachmann_MSB2011](https://github.com/Data2Dynamics/d2d/wiki/Bachmann_MSB2011) and [Swameye_PNAS2003](https://github.com/Data2Dynamics/d2d/wiki/Swameye_PNAS2003).

Best,
Raphael
